name: CI

on: [push]

jobs:
  contracts:
    name: Test Smart Contracts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Validate Formatting
        run: yarn format

      - name: Test Compilation
        run: yarn run compile

      - name: Test Contracts
        run: |
          yarn run test_setup
          yarn run test

  testenv:
    name: Testenv Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get Artifacts
        run: yarn install

      - name: Install
        working-directory: ./packages/testenv/
        run: yarn install

      - name: Test Deployment
        working-directory: ./packages/testenv/
        run: |
          yarn run compile
          yarn run deploy -e

  crypto-ipfs:
    name: ErasureCrypto Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '11.x'
      - name: Install
        working-directory: ./packages/crypto-ipfs/
        run: yarn install
      - name: Run Tests
        working-directory: ./packages/crypto-ipfs/
        run: yarn run test

  pyerasureclient:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6.x', '3.7.x', '3.8.x']
    name: Python Erasure Client v${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install
        working-directory: ./python-packages/erasure-client
        run: make install-dev
      - name: Style
        working-directory: ./python-packages/erasure-client
        run: make style
      - name: Lint
        working-directory: ./python-packages/erasure-client
        run: make lint
      - name: Test
        working-directory: ./python-packages/erasure-client
        run: make test
